### ISSUE TITLE
eic_harvest_hostkeys EC2 check fails on Nitro Instances

### ISSUE THREAD

**Issue by joelthompson** [aws/aws-ec2-instance-connect-config#1]
This: https://github.com/aws/aws-ec2-instance-connect-config/blob/d9988392a29b3f7dad660c17a391fb39dd7c293e/src/bin/eic_harvest_hostkeys#L18-L20

doesn't implement the support for Nitro instances in eic_curl_authorized_keys at https://github.com/aws/aws-ec2-instance-connect-config/blob/d9988392a29b3f7dad660c17a391fb39dd7c293e/src/bin/eic_curl_authorized_keys#L30-L40

As a result, when eic_harvest_hostkeys is run on a Nitro instance, it immediately hits the `exit 0` condition and never uploads its public host keys.

**Comment by LordAlfredo** [comment]
Thank you for bringing this to our attention.  We have addressed this issue in [the lastest commit](https://github.com/aws/aws-ec2-instance-connect-config/commit/99b94d6596ae93ca416b4a9f96a30dac9c7cc0e4) and the fix will be included in the next package release.  We have other guardrails downstream that allow the EC2 Console to trust affected instances in the meantime.
