### ISSUE TITLE
Instance connect does not work with Instance Metadata Service V2

### ISSUE THREAD

**Issue by megaproaktiv** [aws/aws-ec2-instance-connect-config#11]
AWS instance connect (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) enhanced the security of ssh connections.

This instance connect config connect to the imds in the "v1" way:

```bash

curl_cmd="/usr/bin/curl -s -f -m 1"

# Verify the instance ID itself
instance=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/instance-id/")
```

Instead it should do

```bash

TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
curl_cmd='/usr/bin/curl  -H "X-aws-ec2-metadata-token: $TOKEN" -s -f -m 1'


# Verify the instance ID itself
instance=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/instance-id/")
```

I tried to create a patch, but because the development environment is not described I tried with amazon linux 2, but the integration tests does not run. There is also a region "us-east-1" hard coded instead of $region.

How to reproduce:

## OK

1) start instance
2) use instance connect to connect
3) ok

### NOK

1) modifiy settings:
`      - aws ec2 modify-instance-metadata-options --instance-id {{.INSTANCEID}} --http-endpoint enabled --http-token required`
 2) use instance connect to connect
3) Get permission denied:

```bash
mssh i-0416fa9ebc6824ed0
ec2-user@3.121.109.65: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

Version: ec2-instance-connect-1.1-11.amzn2.noarch

**Comment by LordAlfredo** [comment]
This is one of our current top priorities.  We are going through internal reviews and hope to have this out in the near future.

**Comment by LordAlfredo** [comment]
I have just pushed [a commit](https://github.com/aws/aws-ec2-instance-connect-config/commit/47de50509ed43f0c294513841739afb059d5900e) that includes this among a few other curl-related improvements.  We are working to schedule official release to Amazon Linux and Ubuntu repositories in the near future.
