### ISSUE TITLE
incomplete sentence in README.md

### ISSUE THREAD

**Issue by setharnold** [aws/aws-ec2-instance-connect-config#17]
Hello, the following sentence in the README.md appears to have been left incomplete:

> It then reads the ssh host keys on the machine, then creates and signs an AWS Signature Version 4 Request to

Thanks

**Comment by VikashKumarInd** [comment]
Thanks Seth for letting us know about this. I have added this in our backlog to fix the documentation.

**Comment by ohitspaul** [comment]
Addressed as part of https://github.com/aws/aws-ec2-instance-connect-config/commit/215bbe4c607a647dbe8fadc95bce4789d8819384
