### ISSUE TITLE
metadata gives SHA256 for OCSP, but ec2-instance-connect only verify by SHA 1 and cause ALL connections refused

### ISSUE THREAD

**Issue by lisbethw1130** [aws/aws-ec2-instance-connect-config#26]
so ec2-instance-connect use http://169.254.169.254/latest/meta-data/managed-ssh-keys/signer-ocsp to check the OCSP, the instance metadata usually gaves the following in normal
```
06B25927C42A721631C1EFD9431E648FA62E1E39
8484DD8720EC8B1747641469A796F913E9AEDE33
917E732D330F9A12404F73D8BEA36948B929DFFC
```
which is correct, but in one of our machine, the metadata server accidentally gaves
```
0A8E2B0EFF0E33554642700839AB84B1700A95FD3AAEE9F529828E38DC7A0A6D
28689B30E4C306AAB53B027B29E36AD6DD1DCF4B953994482CA84BDC1ECAC996
87DCD4DC74640A322CD205552506D1BE64F12596258096544986B4850BC72706
F55F9FFCB83C73453261601C7E044DB15A0F034B93C05830F28635EF889CF670
```
which all become SHA256

but the ec2-instance-connect only verify by SHA-1(https://github.com/aws/aws-ec2-instance-connect-config/blob/master/src/bin/eic_parse_authorized_keys#L53)

This failure cause all SSH connection made by ec2-instance-connect failed

not sure what is going on

We haven't changed any settings, not sure whether ec2-instance-connect need to fix it, or there's some button on Amazon console that can change the digest type

**Comment by ohitspaul** [comment]
Hi @lisbethw1130, this may have been related to a brief outage during that time period - this has since been resolved. Are you still having the issue?

**Comment by lisbethw1130** [comment]
no, the issue resolved. Thank you
