### ISSUE TITLE
"No Secret Key" Error in 'make deb' Command 

### ISSUE THREAD

**Issue by mtweimer** [aws/aws-ec2-instance-connect-config#3]
When attempting to package the ec2-instance-connect on a debian-based linux machine, I am receiving the following error message: 

<img width="570" alt="Screen Shot 2019-07-30 at 11 12 04 AM" src="https://user-images.githubusercontent.com/49727924/62146395-ee1c3d00-b2ba-11e9-9b94-80979c33dc1f.png">

Do need to replace and add a gpg key somewhere or can I --recv-key from somewhere? This is occurring when I run the 'make deb' command to package the debian version of ec2-instance-connect. 

Thanks in advance, 
Michael

**Comment by LordAlfredo** [comment]
`make deb` is based on debuild, which will try to sign with a local gpg key - you will need to generate and configure one.  I apologize for not documenting this more clearly in our README.

As an alternative to `make deb` you may check out the source package from Ubuntu's package archive via `apt-get source` (or similar mechanisms) and then build from the source package.  You may still need a gpg key configured depending on how you build.

**Comment by mtweimer** [comment]
Thank you for that.. I am still running into a small issue when trying to install, ec2-instance-connect on debian-based linux.. when running the ./make_deb version release command, I receive the following error message: 

![Screen Shot 2019-08-13 at 4 33 49 PM](https://user-images.githubusercontent.com/49727924/62979393-4ee26400-bde9-11e9-9067-33f1c8d5d5f8.png)

It seems like it is not missing the ec2-instance-connect.service and 95-ec2-instance-connect.preset files.  I do not know if I am missing something when grabbing the files or if there are other prerequisites that I am not following.  Looking in the debian/install file, am I missing these files/folders that are being referred to?  Sorry for the confusion.

**Comment by ohitspaul** [comment]
Closing issue - please re-open if you (or someone else) needs more assistance with the issue.
