### ISSUE TITLE
Instance with no outbound connectivity seems to suffer from startup delay 

### ISSUE THREAD

**Issue by dorki** [aws/aws-ec2-instance-connect-config#8]
For some time i was wondering why my ec2 instances takes ~2 minutes to be available to ssh connections. 

By looking at the /var/log/secure I've noticed that there is a 2min gap (each time) between instance startup and the daemon startup:

> Sep 28 22:44:50 ... useradd[3212]: add 'ec2-user' to shadow group 'wheel'
Sep 28 22:44:50 ... useradd[3212]: add 'ec2-user' to shadow group 'systemd-journal'
Sep 28 22:47:02 ... sshd[3401]: Server listening on 0.0.0.0 port 22.
Sep 28 22:47:02 ... sshd[3401]: Server listening on :: port 22.

after some digging, i've notice this in the journalctl:

> Sep 28 22:44:51 ... systemd[1]: Started OpenSSH Server Key Generation.
Sep 28 22:44:51 ... systemd[1]: Starting EC2 Instance Connect Host Key Harvesting...
Sep 28 22:44:51 ... cloud-init[3225]: Cloud-init v. 18.2-72.amzn2.0.7 running 'modules:config' at Sat, 28 Sep 2019 22:44:51 +0000. Up 9.55 seconds.
Sep 28 22:44:51 ... eic_harvest_hostkeys[3284]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Sep 28 22:44:51 ... eic_harvest_hostkeys[3284]: Dload  Upload   Total   Spent    Left  Speed
Sep 28 22:44:51 ... systemd[1]: Stopping OpenSSH Server Key Generation...
Sep 28 22:44:52 ... chronyd[2695]: Selected source 169.254.169.123
Sep 28 22:44:53 ... dhclient[3035]: XMT: Solicit on eth0, interval 3970ms.
Sep 28 22:44:57 ... dhclient[3035]: XMT: Solicit on eth0, interval 7990ms.
Sep 28 22:45:05 ... dhclient[3035]: XMT: Solicit on eth0, interval 16040ms.
Sep 28 22:45:05 ... systemd[1]: Started Dynamically Generate Message Of The Day.
Sep 28 22:45:21 ... dhclient[3035]: XMT: Solicit on eth0, interval 31440ms.
Sep 28 22:45:52 ... dhclient[3035]: XMT: Solicit on eth0, interval 61220ms.
Sep 28 22:46:54 ... dhclient[3035]: XMT: Solicit on eth0, interval 112830ms.
Sep 28 22:47:02 ... systemd[1]: ec2-instance-connect.service: main process exited, code=exited, status=7/NOTRUNNING
Sep 28 22:47:02 ... eic_harvest_hostkeys[3284]: [10.2K blob data]
Sep 28 22:47:02 ... systemd[1]: Failed to start EC2 Instance Connect Host Key Harvesting.
Sep 28 22:47:02 ... systemd[1]: Unit ec2-instance-connect.service entered failed state.
Sep 28 22:47:02 ... systemd[1]: ec2-instance-connect.service failed.
Sep 28 22:47:02 ... systemd[1]: Starting OpenSSH server daemon...
Sep 28 22:47:02 ... sshd[3401]: Server listening on 0.0.0.0 port 22.
Sep 28 22:47:02 ... sshd[3401]: Server listening on :: port 22.

its seems like the Host Key Harvesting causing the delay, and only after it fails, the sshd is started.
i've verified this by these two steps, each one individually solved the problam
1. add Security-Group rule to allow outbound traffic.
2. uninstall the instance-connect tool from the ec2 instance (as shown here https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-uninstall.html) 

Since the instnace-connect tool comes by default with AmazonLinux2, i cannot avoid having this issue on each fresh instance creation.

**Comment by LordAlfredo** [comment]
Argh.  Yeah, that makes sense. What's happening is the eic_harvest_hostkeys script is bound to a systemd unit set to run before sshd (basically as soon as hostkey generation/configuration is finished) and, as part of the script, make a call to ec2-instance-connect.[region].amazonaws.com.  Of course, if the security group is blocking all outbound traffic then it wouldn't be able to reach that even if it is an Amazon endpoint.

There's already some safety checks to fast-fail if we detect we're not running on an EC2 instance.  The fix here will be to add an additional check to this flow for if the service is reachable.  The side effect is that the service will not know your instance's host key, as a result the first time you connect with the EC2 Console's Connect dialog there will be a small additional delay.

**Comment by dorki** [comment]
thanks for the quick reply.
By "EC2 Console's Connect" you are referring to the java ssh client ?
and any way, I cant think of a reason why not to fire the sshd right away (before eic_harvest_hostkeys), and if the eic_harvest_hostkeys completed successfully restart the sshd. because as far as i know, restarting sshd will not kill any active connections since each one become child ssh server and can live without the master server.

**Comment by fernando-villalba** [comment]
I am having issues with this as well when using a private intranet. Is there any endpoint that can be configured to access this? Also, are there any endpoints? I can't find them.

**Comment by CptTZ** [comment]
> I am having issues with this as well when using a private intranet. Is there any endpoint that can be configured to access this? Also, are there any endpoints? I can't find them.

Endpoint varies based on the region of the instance, e.g. in *US West (Oregon)*, the endpoint would be `https://ec2-instance-connect.us-west-2.amazonaws.com/`. `eic_harvest_hostkeys` provided a way to get this endpoint programmatically, you can take that as a reference. Anyway, I believe you have to configure your private intranet in order to reach this endpoint.

We are currently working on a fix for such scenario to address the delay issue as mentioned above.

**Comment by fernando-villalba** [comment]
I meant a [private vpc endpoint ](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html)that could be setup for this. The endpoint "ec2-instance-connect" or anything like it does not seem to exist as an internal endpoint (at least not in eu-west-1).

**Comment by CptTZ** [comment]
@fernando-villalba Thanks for correcting me! I was think about domain whitelisting for VPC egress gateway.

We does not support PrivateLink endpoints at this time. I will put a feature request for supporting this in our backlog.

**Comment by ohitspaul** [comment]
This issue has been addressed a while ago, with the timeout added here: https://github.com/aws/aws-ec2-instance-connect-config/blob/master/src/bin/eic_harvest_hostkeys#L164-L166

I believe this was kept open to "track" PrivateLink endpoints. Re-opened https://github.com/aws/aws-ec2-instance-connect-config/issues/18 for further discussion around PrivateLink, as that issue is directly relevant.
